# ------Linear algebra basic assignment:-------
___by Abdulla Mamun__

  TODO: Solve the given problem and as well write down the markdown explaining the term and its equation in latex form.
  
  should include:
   -   what is ?
   -   proprty of
   -   formula
      
  eg: Transpose of matrix: 
      - what is Transpose? 
      - formula for Transpose
      - Properties of Transpose
https://www.web-formulas.com/Math_Formulas/Linear_Algebra_Properties_of_Transposes.aspx

# Import necessary libraries for this assignment task

In [1]:
import numpy as np
from scipy.stats import ortho_group
from scipy.sparse import csr_matrix as csr
import scipy.linalg as la

# Define a symmertic 3x3 matric and print the transpose of the symmetric matrix

- A symmetric matrix should be

    - square and is equal to its transpose, i.e., A=AT. 
    - If swapping indices doesn't change its components, i.e., aij=aji.
    - The sum and difference between two metrics is symmetric.
    - The inverse of symmetric matrix is also symmetric.
    - It should be diagonalizable that means same elements in both lower and upper triangle. 


The Example of symmetric matrix is :
     \begin{matrix}
        1 & 3 & 4 \\
        3 & 45 & 8 \\
        4 & 8 & 78 
    \end{matrix}

In [2]:
# create a 3x3 matrix
c = np.array([[1,3,4],[3,45,8], [4,8,78]])
print(f"3x3 matrix is: \n {c}")

3x3 matrix is: 
 [[ 1  3  4]
 [ 3 45  8]
 [ 4  8 78]]


In [3]:
# Transpose the matrix c
d = c.T
print(f"After transpose the matrix 3x3 is: \n {d}")

After transpose the matrix 3x3 is: 
 [[ 1  3  4]
 [ 3 45  8]
 [ 4  8 78]]


The matrix c fullfill the symmetric metric conditions, so we can conclude that matrix c is symmetric, though its same dimension, value, diagonal after transpose.

# With the 3x3 matrix calculate the 
- lower traingular matrix
- upper triangular matrix

- A __lower triangular matrix__ is a matrix which only has elements in its lower triangular and remaining elements are 0.

    Example:
    \begin{matrix}
        1 & 0 & 0 \\
        2 & 1 & 0 \\
        3 & 2 & 1 
    \end{matrix}
   


- A __upper triangular matrix__ is a matrix which only has elements in its upper triangular and remaining elements are 0.

    Example:
    \begin{matrix}
        1 & 2 & 3 \\
        0 & 1 & 2 \\
        0 & 0 & 1 
    \end{matrix}
    
    
    
- __Properties__
  - The sum of two upper triangular matrices is upper triangular.
  - The product of two upper triangular matrices is upper triangular.
  - The inverse of an upper triangular matrix, where extant, is upper triangular.
  - The product of an upper triangular matrix and a scalar is upper triangular.
 - use cases: decomposition matrix

In [4]:
print("Original matrix : ", d)
# Create a lower triangular matrix from the previous square matrix d
lower_triangle = np.tril(d)

print(f"Lower Triangular Matrix : \n {lower_triangle}")

# Create a upper triangular matrix from the previous square matrix d
upper_triangle = np.triu(d)

print(f"Upper Triangular Matrix : \n {upper_triangle}")

Original matrix :  [[ 1  3  4]
 [ 3 45  8]
 [ 4  8 78]]
Lower Triangular Matrix : 
 [[ 1  0  0]
 [ 3 45  0]
 [ 4  8 78]]
Upper Triangular Matrix : 
 [[ 1  3  4]
 [ 0 45  8]
 [ 0  0 78]]


# Define a 5x3 matrix and get the :
- diagonal vector
- get diagonal matrix form vector

A diagonal matrix is a matrix in which the entries outside the main diagonal are all zero; the term usually refers to square matrices. 
An example of a 2×2 diagonal matrix is 
${\displaystyle \left[{\begin{smallmatrix}3&0\\0&2\end{smallmatrix}}\right]}$

- while an example of a 3×3 diagonal matrix is 
${\displaystyle \left[{\begin{smallmatrix}6&0&0\\0&7&0\\0&0&4\end{smallmatrix}}\right]}$

- An identity matrix of any size, or any multiple of it (a scalar matrix), is a diagonal matrix.
- A matrix is diagonal if and only if it is triangular and normal.
- A matrix is diagonal if and only if it is both upper- and lower-triangular.
- A diagonal matrix is symmetric.

In [5]:
# Define a 5x3 matrix
a = np.arange(1,16).reshape(5,3)
print("The rectangular form of 5x3 matrix :\n", a)

The rectangular form of 5x3 matrix :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [6]:
# Diagonal elements 
diagonal_vector = np.diag(a)
print("The diagonal elements of a rectangular matrix  a :\n",diagonal_vector)

The diagonal elements of a rectangular matrix  a :
 [1 5 9]


In [7]:
# create the diagonal matrix with diagonal elements
diagonal_matrix = np.diag(diagonal_vector )
print("The diagonal matrix from diagonal vector is : \n", diagonal_matrix)

The diagonal matrix from diagonal vector is : 
 [[1 0 0]
 [0 5 0]
 [0 0 9]]


# create a Identiy matrix

- An identity matrix is a square matrix with diagonal elements 1.
- The rows and columns of the Identity matrix is linearly independent
- It can be expressed as 
   $A \cdot A^{-1} = A^{-1} \cdot A = \mathcal{I}$ 
- it is also called unit matrix. 

- The identity matrix of size n is the n × n square matrix with ones on the main diagonal and zeros elsewhere.
 $\begin{bmatrix}
        1 & 0 & 0  \\
        0 & 1 & 0  \\
        0 & 0 & 1
     \end{bmatrix}$

In [8]:
identity_matrix = np.identity(3)
identity_matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
A = np.random.randint(2,10, size =(2,2))
A

array([[2, 4],
       [5, 6]])

In [10]:
A_= np.linalg.inv(A)
A_

array([[-0.75 ,  0.5  ],
       [ 0.625, -0.25 ]])

In [11]:
A.dot(A_)

array([[ 1.00000000e+00,  0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00]])

In [12]:
a = np.array([1,2,3])
b = np.identity(3)
a.dot(b)

array([1., 2., 3.])

# Define a orthogonal matrix and get:
- inverse of matrix
- show that
 $Q.Q^T=I$ 
 
 where Q is the orthogonal matrix

- An orthogonal or orthonormal matrix is a real square matrix whose columns and rows are orthonormal vectors. 
- Two vectors are orthonormal if they are perpendicular to each other and are unit vectors.

- Mathematically it implies, $Q_{n\times n}$ is a orthogonal matrix if $Q^TQ = Q Q^T = \mathcal{I} \implies Q^T = Q^{-1}$.

__Properties:__
    - The determinant of an orgthogonal matrix is $\pm 1$.
    - A real square matrix is orthogonal if and only if its columns form an orthonormal basis of the Euclidean space ℝn with the ordinary Euclidean dot product.
    

In [13]:
np.set_printoptions(suppress=True, precision = 3) # Remove precision errors with the dot product

# Create a orthogonal matrix 
q = ortho_group.rvs(dim=3) # This creates a orthogonal matrix of size nxn


print("A random orthogonal matrix: \n ", q, "\n")


# Create tranpose of orthogonal matrix
q_t = q.T
print("Transpose of q matrix :\n ", q_t, "\n")

print("The dot product of q and transpose of q is : \n", np.dot(q, q_t))

A random orthogonal matrix: 
  [[-0.102  0.62   0.778]
 [-0.87   0.323 -0.372]
 [ 0.482  0.715 -0.507]] 

Transpose of q matrix :
  [[-0.102 -0.87   0.482]
 [ 0.62   0.323  0.715]
 [ 0.778 -0.372 -0.507]] 

The dot product of q and transpose of q is : 
 [[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


In [14]:
print("Inverse of q:\n", np.linalg.inv(q))

Inverse of q:
 [[-0.102 -0.87   0.482]
 [ 0.62   0.323  0.715]
 [ 0.778 -0.372 -0.507]]


In [15]:
q = np.array([[1,0],[0,-1]])
q

array([[ 1,  0],
       [ 0, -1]])

In [16]:
q.dot(q.T)

array([[1, 0],
       [0, 1]])

In [17]:
q ==q.T

array([[ True,  True],
       [ True,  True]])

In [18]:
b = np.linalg.inv(q)
b

array([[ 1.,  0.],
       [-0., -1.]])

In [19]:
q==b

array([[ True,  True],
       [ True,  True]])

The above code example proves the condition is true for orthogonal matrix.

# Define a matrix and calulate the trace of matrix

__A matrix__ is defined as a rectangular array or table of numbers, symbols, or expressions, arranged in rows and columns.

__The trace__ of a square matrix is defined as the sum of its diagonal elements.
Mathematically,
    \begin{equation}
    trace(A_{n\times n}) = \sum_{i=0}^n a_{i,i}
    \end{equation}
    where $a_{i,j}$ is the element of $i^{th}$ row and $j^{th}$ column of the matrix A.
__Properties of trace :__
- The trace of a sum of two matrices is equal to the sum of their trace.
    \begin{equation}
    trace(A_{n\times n} + B_{n \times n}) = trace{(A_{n \times n})} + trace{(B_{n \times n})}
    \end{equation}
- Trace of a matrix is invariant under transpose
    
- A scalar is equal to its trace :
    \begin{equation}
    A_{1\times n}B_{n \times 1} = trace(AB) = trace(BA)
    \end{equation}

In [20]:
a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print(a)
print("Trace of matrix is", np.trace(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace of matrix is 15


# define a 3x3 matrix and calc determinant, ie not invertable
- Determinant is defined as a scaler value from a square matrix, identity matrix, transpose matrix. 
- A non invertible matrix is one which has determinant=0
-use case: solution of linear regression

In [21]:
a = np.arange(9).reshape(3,3)
print(a)
print("Determinant of a matrix is : \n ", np.linalg.det(a))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Determinant of a matrix is : 
  0.0


As result shows the determinant is zero, so its not invertible matrix.

# create a 2x2 matrix , 1x3 matrix and calculate the rank of the matrix

__Rank of a matrix:__ The dimension (number of linear independent columns) of the range of A-matrix is called the rank of A matrix.
- rank 3 of matrix A: when A is non-singular and A is not eqaul to zero.
- rank 2 of a matrix A: when A is singular(A=0) and at least one of its sub-matrix is non zero.
- rank 1 of a matrix A: when A is singular,i.e. identity matrix.

In [22]:
A = np.random
B = np.random.randint(low=-100, high=100, size=(1,3))

print("The matrices A and B are:\n A: \n",A, "\n B: \n", B)

print(f"Ranks of A is {np.linalg.matrix_rank(A)} and that of B is {np.linalg.matrix_rank(B)}")

The matrices A and B are:
 A: 
 <module 'numpy.random' from '/home/mamun216/miniconda3/lib/python3.8/site-packages/numpy/random/__init__.py'> 
 B: 
 [[ 22  83 -24]]
Ranks of A is 1 and that of B is 1


In [23]:
a_2x2 = np.random.randint(1, 10, size= (2,2))

a_1x3 = np.random.randint(20, 30, size = (1,3))

print("The matrix of a_2x2 is : \n", a_2x2)
print("\n")
print("The matrix of a_1x3 is : \n", a_1x3)

The matrix of a_2x2 is : 
 [[6 8]
 [2 4]]


The matrix of a_1x3 is : 
 [[23 28 28]]


In [24]:
print(f"The rank of a_2x2 matrix is {np.linalg.matrix_rank(a_2x2)}")
print("\n")     
print(f"The rank of a_1x3  matrix is {np.linalg.matrix_rank(a_1x3)}")

The rank of a_2x2 matrix is 2


The rank of a_1x3  matrix is 1


In [25]:
a = np.identity(2)
a

array([[1., 0.],
       [0., 1.]])

In [26]:
np.linalg.matrix_rank(a)

2

In [27]:
b = np.zeros([3,3])
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.linalg.matrix_rank(b)

0

# create a 3*6 matrix with zeros and ones and count the zeros in matrix 
- also find the size of matrix
- calculate the matrix sparsity: count of zeros/size of matrix

In [29]:
one_zero = np.random.choice([0,1], size = (3,6))

print("Matrix with zeros and ones: \n", one_zero)

print("counts for zeros", np.sum(one_zero==0))

print("Size of the matrix, ie. the number of rows and columns :", one_zero.size)

print("Sparsity of the matrix :", np.unique(one_zero, return_counts = True)[0]/one_zero.size)

Matrix with zeros and ones: 
 [[0 1 0 0 0 1]
 [0 1 0 0 1 0]
 [0 1 1 0 1 0]]
counts for zeros 11
Size of the matrix, ie. the number of rows and columns : 18
Sparsity of the matrix : [0.    0.056]


# convert the sparse using csr method and again reconstruct to dense
A = array([
    [1, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 1],
    [0, 0, 0, 2, 0, 0]
]) #dense matrix

https://www.youtube.com/watch?v=fy_dSZb-Xx8

In [30]:
A = np.array([[1, 0, 0, 1, 0, 0], [0, 0, 2, 0, 0, 1], [0, 0, 0, 2, 0, 0]]) 
A

array([[1, 0, 0, 1, 0, 0],
       [0, 0, 2, 0, 0, 1],
       [0, 0, 0, 2, 0, 0]])

In [31]:
# Create sparse matrix with csr (compressed spaced row) method
sparse_mat = csr(A)
print(sparse_mat)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [32]:
print("reconstructing to dense \n", sparse_mat.todense())

reconstructing to dense 
 [[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


# define a tensor of matrix of shape (3,3,3)

In [33]:
tensor1 = np.arange(27).reshape((3,3,3))
print(tensor1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


# create a 2 tensor of size (3,3,3) and perform:
- tensor additon
- tensor substraction


In [34]:
tensor1 = np.arange(27).reshape(3,3,3)
tensor2 = np.arange(27).reshape(3,3,3)
print("Tensor1 :\n", tensor1, "\n", "Tensor2 :\n", tensor2)

Tensor1 :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 
 Tensor2 :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [35]:
# Tensor addition
print("Addition : \n", np.add(tensor1,tensor2))

Addition : 
 [[[ 0  2  4]
  [ 6  8 10]
  [12 14 16]]

 [[18 20 22]
  [24 26 28]
  [30 32 34]]

 [[36 38 40]
  [42 44 46]
  [48 50 52]]]


In [36]:
# Subtraction Tensor subtraction
print("subtraction:\n",np.subtract(tensor1, tensor2))

subtraction:
 [[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


# perform a Hadamard Product for the above tensor

- For two matrices A and B, the Hadamard product A∘B is the matrix obtained by (A∘B)i,j=Ai,jBi,j.
- The Hadamard product is a binary operation between 2 matrices (or tensors) of same dimensions 
- and produces an elementwise product of the 2 matrices(or tensors) such that the output matrix (or tensor) has the same dimention of the input.

In [37]:
print("The Hadamard product between the 2 above tensors :\n", tensor1*tensor2)

The Hadamard product between the 2 above tensors :
 [[[  0   1   4]
  [  9  16  25]
  [ 36  49  64]]

 [[ 81 100 121]
  [144 169 196]
  [225 256 289]]

 [[324 361 400]
  [441 484 529]
  [576 625 676]]]


# Perform a Tensor division for a tensor of shape  T1 and T2 of shape(4,3,3) 

In [38]:
T1 = np.random.randint(low= 10, high = 20, size=(4,3,3))
T2 = np.random.randint(low= 10, high = 20, size=(4,3,3))

print(f"The tensors are Tensor 1 : \n{T1}\n and Tensor 2 : \n {T2} and the division is \n{np.divide(T1, T2)}")

The tensors are Tensor 1 : 
[[[11 16 15]
  [15 18 11]
  [11 17 19]]

 [[17 18 19]
  [18 17 15]
  [15 16 16]]

 [[17 17 17]
  [18 14 10]
  [16 10 17]]

 [[19 14 10]
  [17 19 11]
  [18 17 10]]]
 and Tensor 2 : 
 [[[19 14 10]
  [19 12 19]
  [17 12 17]]

 [[11 11 19]
  [16 12 19]
  [13 14 11]]

 [[12 17 14]
  [12 16 17]
  [17 17 12]]

 [[15 16 18]
  [19 15 16]
  [12 10 10]]] and the division is 
[[[0.579 1.143 1.5  ]
  [0.789 1.5   0.579]
  [0.647 1.417 1.118]]

 [[1.545 1.636 1.   ]
  [1.125 1.417 0.789]
  [1.154 1.143 1.455]]

 [[1.417 1.    1.214]
  [1.5   0.875 0.588]
  [0.941 0.588 1.417]]

 [[1.267 0.875 0.556]
  [0.895 1.267 0.688]
  [1.5   1.7   1.   ]]]


# define a 2 tensor of 2x2 and calculate the tensor product

In [39]:
T3 = np.random.randint(low= 1, high = 10, size=(2,2))
T4 = np.random.randint(low= 1, high = 10, size=(2,2))

tensor_product = np.tensordot(T3,T4, axes = 0)
print("Tensor product", tensor_product)

Tensor product [[[[24 18]
   [ 3 12]]

  [[72 54]
   [ 9 36]]]


 [[[72 54]
   [ 9 36]]

  [[40 30]
   [ 5 20]]]]


# calulate the factorization factors a matrix(Lu) decompostion for an array of shape 3x3
- reconstruct the original matrix from the decompostion

The LU decompostion of a matrix is a type of factorization which factors the matrix into a product of an upper triangular and lower triangular matrix.

   For a matrix $A_{n \times n}$, An LU factorization refers to the factorization of A, with proper row and/or column orderings or permutations, into two factors – a lower triangular matrix L and an upper triangular matrix U
    \begin{equation}
    A = L U
    \end{equation}
    
   where $L$ is a lower-triangular matrix and $U$ is a upper-triangular matrix.

In [40]:
M = np.arange(9.0).reshape(3,3)
M

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [41]:
permu,lowerT, upperT = la.lu(M, permute_l = False)
print("permutation ", permu)
print("\n")
print("lower triangle", lowerT)
print("\n")
print("upper triangle", upperT)

permutation  [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


lower triangle [[1.  0.  0. ]
 [0.  1.  0. ]
 [0.5 0.5 1. ]]


upper triangle [[6. 7. 8.]
 [0. 1. 2.]
 [0. 0. 0.]]


In [42]:
# Recontruction to the original matrix
origin = np.dot(permu,lowerT)
print("original matrix : \n", origin.dot(upperT))

original matrix : 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


# from a matrix of shape 3x2
- calculate the QR decompostion
- reconstruct the original matrix

The QR decompostion of the matrix decomposes a matrix to a product of 2 components, an orthogonal matrix and an upper triangular matrix.

- For a matrix $A_{m \times n}$, the QR decomposition gives $A = QR$ where $Q$ is an orthogonal matrix and $R$ is an upper triangular matrix.
- The QR decompostion can be achieved by numerous algorithms - Gram–Schmidt process, Householder transformations, or Givens rotations.

-- use case svd

In [43]:
A = np.random.randint(low=0, high=10, size=(3,2))
print("The matrix of shape 3x2 is \n", A)

q,r = np.linalg.qr(A)

The matrix of shape 3x2 is 
 [[2 3]
 [5 1]
 [9 8]]


In [44]:
q,r = np.linalg.qr(A)

print("Orthogonal part", q)

Orthogonal part [[-0.191  0.442]
 [-0.477 -0.822]
 [-0.858  0.359]]


In [45]:
print("Upper triangular part ", r)

Upper triangular part  [[-10.488  -7.914]
 [  0.      3.372]]


In [46]:
# Reconstruction
b = q.dot(r)
b

array([[2., 3.],
       [5., 1.],
       [9., 8.]])

# define a 3x3 matrix calculate
- cholesky decomposition using lower factorize
- reconstruct the original matrix

The Cholesky decomposition is a decomposition of a Hermitian, positive-definite matrix into the product of a lower triangular matrix and its conjugate transpose.

   Mathematically, the cholesky decompostion of a positive-definite matrix, $A_{n \times n}$ is $A = L L^*$ (for $A$ in complex space ) and $A = LL^T$ ($A$ in real space),    
    where $L$ is a lower triangular matrix with real and positive diagonal entries, and $L^*$ denotes the conjugate transpose of $L$. 
- use case: earlier to solve OLS(ordinary least square)

In [47]:
A= np.random.randint(0,5, size=(3,3))

D = np.diag(np.random.randint(1,5, size=(3)))
positive_definite = A.T.dot(D).dot(A)

print("Matrix:\n",positive_definite)

Matrix:
 [[76 56 32]
 [56 79 31]
 [32 31 19]]


In [48]:
Cholesky = np.linalg.cholesky(positive_definite)
print("The Cholesky decompositon using lower factorize leads to :\n", Cholesky)
print("\n")
print("Reconstruction of the matrix from the decompositon\n", Cholesky.dot(Cholesky.T))

The Cholesky decompositon using lower factorize leads to :
 [[8.718 0.    0.   ]
 [6.424 6.143 0.   ]
 [3.671 1.208 2.017]]


Reconstruction of the matrix from the decompositon
 [[76. 56. 32.]
 [56. 79. 31.]
 [32. 31. 19.]]


# define a 3x3 matrix and calculate the:
- eigendecomposition 


- Eigendecomposition is a method of factorization of a matrix into a canonical form, representing the matrix into eigenvectors and eigenvalues.
- A (non-zero) vector v of dimension N is an eigenvector of a square N × N matrix A if it satisfies the linear equation :
\begin{equation}
    A\mathbf{v} = \lambda \mathbf{v}
\end{equation}
where $\lambda$ is a scalar, the eigenvalue corresponding to the eigenvector $\mathbf{v}$. In a similar fashion we can define a polynomial defining the equation for eigenvalues :

\begin{equation}
 p(\lambda) = determinant(A - \lambda \mathcal{I}) = 0
\end{equation}

   Corresponding to each eigenvalue $\lambda_i$, we havea a specific eigenvalue equation :
   \begin{equation}
   ( A -\lambda _{i}\mathcal {I} )\mathbf {v} =0
   \end{equation}
    
 Given a square matrix $A_{n \times n}$, with $n$ linearly independent eigenvectors, the matrix $A$ can be factorized as :
 \begin{equation}
 A = Q\Lambda Q^{-1}
 \end{equation}

In [70]:
data = np.random.randint(low=0, high=10, size=(3,3))
print("The matrix of shape 3x3 is \n", data)
print("\n")

w,v = np.linalg.eig(data)

print("The eigendecomposition leads to the eigenvalues \n ", w, "\nand eigenvectors \n", v, "\n")

The matrix of shape 3x3 is 
 [[2 8 0]
 [8 8 2]
 [3 9 3]]


The eigendecomposition leads to the eigenvalues 
  [14.828 -4.034  2.207] 
and eigenvectors 
 [[-0.417 -0.733 -0.238]
 [-0.669  0.553 -0.006]
 [-0.615 -0.395  0.971]] 



# from the above eigendecomposition conform an eigenvector and eigenvalue

In [71]:
print("Eigen value :", w)
print("\n")
print("Each row of the eigenvector corresponds to each element of the eigenvalue array indexed sequentially.")
print("Eigen vector :", v)

Eigen value : [14.828 -4.034  2.207]


Each row of the eigenvector corresponds to each element of the eigenvalue array indexed sequentially.
Eigen vector : [[-0.417 -0.733 -0.238]
 [-0.669  0.553 -0.006]
 [-0.615 -0.395  0.971]]


In [72]:
data

array([[2, 8, 0],
       [8, 8, 2],
       [3, 9, 3]])

In [73]:
AV= data.dot(v[:,0])
AV

array([-6.187, -9.921, -9.119])

In [74]:
LV= v[:,0]*w[0]
LV

array([-6.187, -9.921, -9.119])

In [75]:
AV==LV

array([False, False, False])

# Reconstruct the matrix from the Eigendecompostion

In [76]:
recons = np.diag(w)
print("The reconstructed matrix from the eigendecompostion is \n",v.dot(recons)@np.linalg.inv(v))

The reconstructed matrix from the eigendecompostion is 
 [[ 2.  8. -0.]
 [ 8.  8.  2.]
 [ 3.  9.  3.]]


# calculate the L1 norm for a 1x3 matrix
- __L1 norm__ is the total distance covered by a vector from its origin to destination point 
- and it calculated by adding vector manually towards its target point.

In [81]:
L1 = np.array([1,3,3])
print("Matrix : \n", L1, "\n")
print("L1 norm : ", np.linalg.norm(L1,1))

Matrix : 
 [1 3 3] 

L1 norm :  7.0


# calculate the L2 norm for the 1x4 matrix

- __L2 norm__ is the shortest total distance covered by a vector from its origin to destination point 
- and it calculated by eucleadian distance, squarring vector, adding, sum and then square-root.

In [82]:
L2 = np.array([1,3,3,5])
print("1x4 matrix:\n", L2)
print("L2 norm calculation result : \n", np.linalg.norm(L2,2))

1x4 matrix:
 [1 3 3 5]
L2 norm calculation result : 
 6.6332495807108


# Calculate the singular value decomposition(SVD)

In [83]:
data

array([[2, 8, 0],
       [8, 8, 2],
       [3, 9, 3]])

In [84]:
np.linalg.svd(data)

(array([[-0.469,  0.539, -0.699],
        [-0.664, -0.738, -0.123],
        [-0.583,  0.406,  0.704]]),
 array([16.675,  4.164,  1.901]),
 array([[-0.48 , -0.858, -0.184],
        [-0.866,  0.497, -0.062],
        [-0.144, -0.13 ,  0.981]]))

# Pseudoinverse